/*
 * generated by Xtext 2.30.0
 */
package webtest.dsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class WebTestDslProposalProvider extends AbstractWebTestDslProposalProvider {
}
