/*
 * generated by Xtext 2.31.0
 */
package webtest.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWebTestDslScopeProvider extends DelegatingScopeProvider {
}
