package webtest.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class WebTestProjectGenerator {
  public CharSequence generateHelloWorld() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("webtest example.HelloWorld");
    _builder.newLine();
    _builder.newLine();
    _builder.append("test SayHelloTest");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("print \"Hello World!\"");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generateLogback() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
    _builder.newLine();
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<import class=\"ch.qos.logback.classic.encoder.PatternLayoutEncoder\"/>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<import class=\"ch.qos.logback.core.ConsoleAppender\"/>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<appender name=\"STDOUT\" class=\"ConsoleAppender\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<encoder class=\"PatternLayoutEncoder\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -%kvp- %msg%n</pattern>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<root level=\"info\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<appender-ref ref=\"STDOUT\"/>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</root>");
    _builder.newLine();
    _builder.append("</configuration>");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generateLogbackTest() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
    _builder.newLine();
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<import class=\"ch.qos.logback.classic.encoder.PatternLayoutEncoder\"/>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<import class=\"ch.qos.logback.core.ConsoleAppender\"/>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<appender name=\"STDOUT\" class=\"ConsoleAppender\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<encoder class=\"PatternLayoutEncoder\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} -%kvp- %msg%n</pattern>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</encoder>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</appender>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<root level=\"info\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<appender-ref ref=\"STDOUT\"/>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</root>");
    _builder.newLine();
    _builder.append("</configuration>");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generatePomXml(final String projectName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<groupId>webtest</groupId>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<artifactId>");
    _builder.append(projectName, "  ");
    _builder.append("</artifactId>");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("<version>0.0.1-SNAPSHOT</version>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.java>17</version.java>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.maven.compiler>3.11.0</version.maven.compiler>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.maven.surefire>3.1.2</version.maven.surefire>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.selenium>4.11.0</version.selenium>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.junit>5.10.0</version.junit>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.slf4j>2.0.7</version.slf4j>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<version.logback>1.4.11</version.logback>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</properties>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<dependencies>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<groupId>org.slf4j</groupId>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<artifactId>slf4j-api</artifactId>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<version>${version.slf4j}</version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<groupId>ch.qos.logback</groupId>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<artifactId>logback-classic</artifactId>");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<version>${version.logback}</version>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<groupId>org.seleniumhq.selenium</groupId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<artifactId>selenium-chrome-driver</artifactId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<version>${version.selenium}</version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<groupId>org.seleniumhq.selenium</groupId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<artifactId>selenium-java</artifactId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<version>${version.selenium}</version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<groupId>org.junit.jupiter</groupId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<artifactId>junit-jupiter</artifactId>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<version>${version.junit}</version>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<scope>test</scope>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</dependencies>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<build>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<finalName>${project.artifactId}</finalName>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<plugins>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<groupId>org.apache.maven.plugins</groupId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>maven-compiler-plugin</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>${version.maven.compiler}</version>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<release>${version.java}</release>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<plugin>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>maven-surefire-plugin</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>${version.maven.surefire}</version>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<configuration>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("<systemPropertyVariables>");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("<webdriver.chrome.driver>c:/Programs/chromedriver/chromedriver.exe</webdriver.chrome.driver>");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("</systemPropertyVariables>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("</configuration>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</plugin>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</plugins>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</build>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generateClasspath() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<classpath>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"src\" output=\"target/classes\" path=\"src/main/java\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"optional\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"src\" output=\"target/test-classes\" path=\"src-gen/test/java\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"test\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"optional\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry excluding=\"**\" kind=\"src\" output=\"target/classes\" path=\"src/main/resources\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"optional\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"src\" output=\"target/test-classes\" path=\"src/test/java\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"test\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"optional\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry excluding=\"**\" kind=\"src\" output=\"target/test-classes\" path=\"src/test/resources\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"test\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"optional\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"con\" path=\"org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"module\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"con\" path=\"org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<attributes>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<attribute name=\"maven.pomderived\" value=\"true\"/>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</attributes>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</classpathentry>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<classpathentry kind=\"output\" path=\"target/classes\"/>");
    _builder.newLine();
    _builder.append("</classpath>");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generateGitignore() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("target");
    _builder.newLine();
    _builder.append("output");
    _builder.newLine();
    return _builder;
  }
}
